class MovableException(Exception):
    ...


class GetVelocityException(MovableException):
    ...

class GetLocationException(MovableException):
    ...

class SetLocationException(MovableException):
    ...